version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: local-db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      -
  local-db:
    image: library/infra-subway-monitoring:lastest
    container_name: infra-subway-monitoring
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ~/monitoring/log:/workspace/log
    depends_on:
      - local-db
